Jekyll migration (#291)

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,7 +1,7 @@
 format_version: 3
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 description: |
-  Official guides: http://www.mkdocs.org
+  Official guides: https://jekyllrb.com/
 workflows:
   ci:
     before_run:
@@ -12,7 +12,7 @@ workflows:
         - content: |-
             #!/bin/bash
             set -ex
-            mkdocs build
+            jekyll build
   deploy-to-github-pages:
     envs:
     - GOOGLE_ANALYTICS_KEY: 'UA-53276411-1'
@@ -21,7 +21,7 @@ workflows:
     steps:
     - script:
         description: |
-          Note: mkdocs builds into `./site/`
+          Note: Jekyll builds into `./site/`
 
           Official GitHub Pages deploy guide: https://help.github.com/articles/creating-project-pages-manually/
 
@@ -32,8 +32,29 @@ workflows:
             #!/bin/bash
             set -ex
             # Build & Deploy
-            mkdocs build --clean
-            mkdocs gh-deploy
+
+            if [ ! -z "${BITRISE_GIT_BRANCH}" ] ; then
+              # this is an auto-deploy on bitrise.io
+              # allow it only for the "master" branch
+              if [[ "${BITRISE_GIT_BRANCH}" != "master" ]] ; then
+              echo " [!] BITRISE_GIT_BRANCH != 'master' - REQUIRED"
+                exit 1
+              fi
+              # git checkout, so that we're not on Detached HEAD
+              git checkout "${BITRISE_GIT_BRANCH}"
+            fi
+
+            current_branch="$(git rev-parse --abbrev-ref HEAD)"
+            if [[ "${current_branch}" != "master" ]] ; then
+              echo " [!] You're not on the 'master' branch - REQUIRED"
+              exit 1
+            fi
+
+            git pull
+            git checkout gh-pages
+            git pull
+            git merge master
+            git push
   generate-api-docs:
     steps:
     - script@1.1.4:
@@ -51,44 +72,27 @@ workflows:
             # generate gotgen config
             go run _scripts/gen_api_docs_gotgen_config.go
             # move it into docs/api
-            api_docs_dir_pth="./docs/api"
+            api_docs_dir_pth="./_articles/api"
             mv ./gg.conf.json "${api_docs_dir_pth}/gg.conf.json"
             # run gotgen there
             go get -u -v github.com/bitrise-tools/gotgen
             cd "${api_docs_dir_pth}"
             gotgen generate
+
+            echo '---
+            menus: api
+            title: Bitrise.io API v0.1 (Work In Progress)
+            ---' | cat - ./v0.1.md > temp && mv temp ./v0.1.md
   setup:
     steps:
     - script:
-        deps:
-          brew:
-          - name: python
-            bin_name: pip
-          apt_get:
-          - name: python-pip
-          - name: python-dev
-          - name: build-essential
         inputs:
         - content: |
             #!/bin/bash
             set -ex
 
-            sudocmd=""
-            if [[ "$(uname)" == "Linux" ]] ; then
-              sudocmd="sudo"
-            fi
-            pipcmd="pip"
-            if [[ "$(uname)" == "Darwin" ]] ; then
-              pipcmd="pip3"
-            fi
-
-            # On Linux, with apt installed python / python-pip
-            # these commands have to be performed with `sudo`!
-            ${sudocmd} ${pipcmd} install --upgrade pip
-            ${sudocmd} ${pipcmd} install --upgrade virtualenv
-            ${sudocmd} ${pipcmd} install -r requirements.txt
-            mkdocs --version
-            ${pipcmd} show mkdocs-material
+            bundle install
+            npm install
   up:
     steps:
     - script:
@@ -96,4 +100,4 @@ workflows:
         - content: |-
             #!/bin/bash
             set -ex
-            mkdocs serve
+            bundle exec jekyll serve
