Update GitHub pages release

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -32,8 +32,29 @@ workflows:
             #!/bin/bash
             set -ex
             # Build & Deploy
-            jekyll build
-            mkdocs gh-deploy
+
+            if [ ! -z "${BITRISE_GIT_BRANCH}" ] ; then
+              # this is an auto-deploy on bitrise.io
+              # allow it only for the "master" branch
+              if [[ "${BITRISE_GIT_BRANCH}" != "master" ]] ; then
+              echo " [!] BITRISE_GIT_BRANCH != 'master' - REQUIRED"
+                exit 1
+              fi
+              # git checkout, so that we're not on Detached HEAD
+              git checkout "${BITRISE_GIT_BRANCH}"
+            fi
+
+            current_branch="$(git rev-parse --abbrev-ref HEAD)"
+            if [[ "${current_branch}" != "master" ]] ; then
+              echo " [!] You're not on the 'master' branch - REQUIRED"
+              exit 1
+            fi
+
+            git pull
+            git checkout gh-pages
+            git pull
+            git merge master
+            git push
   generate-api-docs:
     steps:
     - script@1.1.4:
